### ISSUE TITLE
Kimchi not throwing errors when migration is performed and gives impression of migration doesn't work

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/kimchi#948]
Problem here is that the UI isn't forwarding the status of the migrate task. The status is being updated in the task but the user is not aware of it.

I have provoked an error by trying to migrate a VM with the same name in both source and destination. No UI error was shown but the task reported it:

[danielhb@louis ~]$ curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET  'https://localhost:8001/plugins/kimchi/tasks/8'
Enter host password for user 'root':

{
  "status":"failed",
  "message":"Unexpected exception: KCHVM0058E: Failed to migrate virtual machine migratedanielhb due error: Requested operation is not valid: domain 'migratedanielhb' is already active",
  "id":"8",
  "target_uri":"/plugins/kimchi/vms/migratedanielhb/migrate"
}

Appropriate errors should be thrown from kimchi.

**Comment by samhenri** [comment]
I think somehow the migration and clone tasks are broken because when I've implemented Live Migration it was throwing errors for domains with the same name and the task for on going clone/migration guests are not showing anything for me. I'll take a look on this.

**Comment by samhenri** [comment]
Patch sent to ML last week but it requires a patch sent for Wok Messages applied first.

**Comment by sstoppler** [comment]
According to test, 2 scenarios were ran and one still shows the problem:

I tried 2 scenarios to provoke error:

1. Tried migrating vm to a destination machine which has the active vm with
same name:

It is working fine as error message "avocado-vt-vm1-Test: Unexpected exception:
KCHVM0058E: Failed to migrate virtual machine avocado-vt-vm1-Test due error:
Requested operation is not valid: domain 'avocado-vt-vm1-Test' is already
active" was thrown from kimchi UI to the user

2. Tried migrating vm without having cache='none' in guest xml:

Here, I couldn't see the error message from Kimchi UI, it behaves same way as
before the fix.

@alinefm - can you reopen this issue or would you like for me to create a new one?  Thanks!

**Comment by samhenri** [comment]
Does the test 2 throws an error message in the running task? If it does then it is a front-end error and I think this issue should be reopen, otherwise it is a back-end error and the failed task should display this error on the tasks message key.

**Comment by sstoppler** [comment]
Request being made to test:

In working w/Daniel, we were not able to reproduce the problem.  cache=none was removed from the guest xml and migration worked.

Would you please send me your VM XML to see if we can reproduce it in our hosts?  Thank you!

**Comment by sstoppler** [comment]
@alinefm @danielhb Should this be reopened until we get further information/confirmation from test based on comments above?
